### ISSUE TITLE
math domain error при запуске на случайных данных

### ISSUE THREAD

**Issue by r-aax** [r-aax/py-avx512#17]
```
Traceback (most recent call last):
  File "C:\Data\VM\Share\r-aax\py-avx512\pyavx512\test.py", line 151, in <module>
    dump_all_cases(['008_pow_ternary'])
  File "C:\Data\VM\Share\r-aax\py-avx512\pyavx512\test.py", line 117, in dump_all_cases
    res_orig = emu.run(ir_orig, input_data)
  File "C:\Data\VM\Share\r-aax\py-avx512\pyavx512\tools\emulator.py", line 66, in run
    self.single_run(ir)
  File "C:\Data\VM\Share\r-aax\py-avx512\pyavx512\tools\emulator.py", line 105, in single_run
    self.emulate_oper(cur_oper)
  File "C:\Data\VM\Share\r-aax\py-avx512\pyavx512\tools\emulator.py", line 161, in emulate_oper
    oper.Res.RuntimeVal = math.pow(oper.Args[0].RuntimeVal, oper.Args[1].RuntimeVal)
ValueError: math domain error
```

**Comment by abagrov** [comment]
@r-aax если это корень из отрицательного числа, что в таком случае делать?

**Comment by r-aax** [comment]
можно туда какой-нибудь NaN записать?

**Comment by r-aax** [comment]
вполне нормально
а что за печать "Block item FuncCall is not implemented"?

**Comment by a-bagrov** [comment]
это когда в коде встречается просто вызов функции, например [здесь](https://github.com/r-aax/py-avx512/blob/6bb0522c51464319dbdfdca076fdac0fb6aad834/cases/012_riemann_starpu.c#L17)
